<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CATALOG [
        <!ENTITY AUTHOR "John Doe">
        <!ENTITY COMPANY "JD Power Tools, Inc.">
        <!ENTITY EMAIL "jd@jd-tools.com">
        <!ELEMENT CATALOG (PRODUCT+)>
        <!ELEMENT PRODUCT
                (SPECIFICATIONS+,OPTIONS?,PRICE+,NOTES?)>

        <!ATTLIST PRODUCT
                NAME CDATA #IMPLIED
                CATEGORY (HandTool|Table|Shop-Professional) "HandTool"
                PARTNUM CDATA #IMPLIED
                PLANT (Pittsburgh|Milwaukee|Chicago) "Chicago"
                INVENTORY (InStock|Backordered|Discontinued) "InStock">

        <!ELEMENT SPECIFICATIONS (#PCDATA)>

        <!ATTLIST SPECIFICATIONS
                WEIGHT CDATA #IMPLIED
                POWER CDATA #IMPLIED>

        <!ELEMENT OPTIONS (#PCDATA)>
        <!ATTLIST OPTIONS
                FINISH (Metal|Polished|Matte) "Matte"
                ADAPTER (Included|Optional|NotApplicable) "Included"
                CASE (HardShell|Soft|NotApplicable) "HardShell">
        <!ELEMENT PRICE (#PCDATA)>
        <!ATTLIST PRICE
                MSRP CDATA #IMPLIED
                WHOLESALE CDATA #IMPLIED
                STREET CDATA #IMPLIED
                SHIPPING CDATA #IMPLIED>

        <!ELEMENT NOTES (#PCDATA)>
        ]>

<CATALOG>
    <PRODUCT>
        <SPECIFICATIONS>HELLO</SPECIFICATIONS>
        <PRICE>1</PRICE>
    </PRODUCT>

    <PRODUCT NAME="HandTool" PARTNUM="Milwaukee" INVENTORY="Discontinued">
        <SPECIFICATIONS WEIGHT="1" POWER="Hight">123</SPECIFICATIONS>
        <SPECIFICATIONS WEIGHT="1">321</SPECIFICATIONS>
        <OPTIONS FINISH="Metal" ADAPTER="Included" CASE="HardShell">456</OPTIONS>
        <PRICE MSRP="A" WHOLESALE="B" STREET="C" SHIPPING="D">7890</PRICE>
        <NOTES>0</NOTES>
    </PRODUCT>
</CATALOG>
